import mongoose from "mongoose";

const ProductSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
    },
    description: String,
    price: Number,
    discount: Number,
    image: [String],
    categories: [{ type: mongoose.Schema.Types.ObjectId, ref: "Categories" }],
    collections: [{ type: mongoose.Schema.Types.ObjectId, ref: "Collection" }],
    subcollections: [{ type: mongoose.Schema.Types.ObjectId, ref: "SubCollection" }],
    tags: [String],
    color1: String,
  color2: String,
  color3: String,
  color4: String,
  color5: String,
  color6: String,
  color7: String,
  color8: String,
  color9: String,
  color10: String,
  color11: String,
  color12: String,
  color13: String,
  color14: String,
  color15: String,
  color16: String,
  color17: String,
  color18: String,
  color19: String,
  color20: String,
  cp1: Number,
  cp2: Number,
  cp3: Number,
  cp4: Number,
  cp5: Number,
  cp6: Number,
  cp7: Number,
  cp8: Number,
  cp9: Number,
  cp10: Number,
  cp11: Number,
  cp12: Number,
  cp13: Number,
  cp14: Number,
  cp15: Number,
  cp16: Number,
  cp17: Number,
  cp18: Number,
  cp19: Number,
  cp20: Number,
  dp1: Number,
  dp2: Number,
  dp3: Number,
  dp4: Number,
  dp5: Number,
  dp6: Number,
  dp7: Number,
  dp8: Number,
  dp9: Number,
  dp10: Number,
  dp11: Number,
  dp12: Number,
  dp13: Number,
  dp14: Number,
  dp15: Number,
  dp16: Number,
  dp17: Number,
  dp18: Number,
  dp19: Number,
  dp20: Number,
  ci1: [String],
  ci2: [String],
  ci3: [String],
  ci4: [String],
  ci5: [String],
  ci6: [String],
  ci7: [String],
  ci8: [String],
  ci9: [String],
  ci10: [String],
  ci11: [String],
  ci12: [String],
  ci13: [String],
  ci14: [String],
  ci15: [String],
  ci16: [String],
  ci17: [String],
  ci18: [String],
  ci19: [String],
  ci20: [String],
  size1: String,
  size2: String,
  size3: String,
  size4: String,
  size5: String,
  size6: String,
  size7: String,
  size8: String,
  size9: String,
  size10: String,
  size11: String,
  size12: String,
  size13: String,
  size14: String,
  size15: String,
  size16: String,
  size17: String,
  size18: String,
  size19: String,
  size20: String,
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
  },
  { toJSON: { getters: true } }
);

const Product =
  mongoose.models.Product || mongoose.model("Product", ProductSchema);

export default Product;
